import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Heart, Bookmark, Check, FileText, Trash2, X } from 'lucide-react';
import Header from '../components/Header';
import Reader from '../components/Reader';
import DictionaryModal from '../components/DictionaryModal';
import { getArticleById } from '../data/articles';
import { Article, FavoriteArticle, Bookmark as BookmarkType } from '../types';
import { useApp } from '../context/AppContext';
import { addReadingTime, addReadingHistory, getNotesByArticle, Note } from '../utils/storage';

const ArticleReaderPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [article, setArticle] = useState<Article | null>(null);
  const [selectedWord, setSelectedWord] = useState<string>('');
  const [selectedSentence, setSelectedSentence] = useState<string>('');
  const startTimeRef = useRef<number>(0);
  const {
    addToFavoriteArticles,
    removeFromFavoriteArticles,
    isArticleFavorited,
    addToBookmarks,
    isBookmarked,
    darkMode,
    notes,
    addToNotes,
    removeFromNotes,
  } = useApp();
  const [selectedText, setSelectedText] = useState<string>('');
  const [showNoteToolbar, setShowNoteToolbar] = useState<boolean>(false);
  const [noteToolbarPosition, setNoteToolbarPosition] = useState<{ x: number; y: number }>({ x: 0, y: 0 });
  const [showNotesList, setShowNotesList] = useState<boolean>(false);
  const [articleNotes, setArticleNotes] = useState<Note[]>([]);

  useEffect(() => {
    if (id) {
      const foundArticle = getArticleById(id);
      if (foundArticle) {
        setArticle(foundArticle);
        // 记录开始阅读时间
        startTimeRef.current = Date.now();
        // 添加到阅读历史
        addReadingHistory({
          articleId: foundArticle.id,
          title: foundArticle.title,
          titleZh: foundArticle.titleZh,
          author: foundArticle.author,
          level: foundArticle.level,
          readAt: new Date().toISOString(),
        });
      } else {
        navigate('/articles');
      }
    }
  }, [id, navigate]);

  // 离开页面时保存阅读时长
  useEffect(() => {
    return () => {
      if (startTimeRef.current > 0) {
        const readingSeconds = Math.floor((Date.now() - startTimeRef.current) / 1000);
        if (readingSeconds > 5) { // 只记录超过5秒的阅读
          addReadingTime(readingSeconds);
        }
      }
    };
  }, []);

  // 更新当前文章的笔记列表
  useEffect(() => {
    if (article) {
      const notesForArticle = notes.filter(n => n.articleId === article.id);
      setArticleNotes(notesForArticle);
    }
  }, [notes, article]);

  // 处理文本选择
  const handleTextSelection = () => {
    const selection = window.getSelection();
    if (selection && selection.toString().trim().length > 0) {
      const text = selection.toString().trim();
      if (text.length >= 2) {
        setSelectedText(text);
        const range = selection.getRangeAt(0);
        const rect = range.getBoundingClientRect();
        setNoteToolbarPosition({
          x: rect.left + rect.width / 2,
          y: rect.top - 10,
        });
        setShowNoteToolbar(true);
      }
    }
  };

  // 添加到笔记
  const handleAddToNotes = () => {
    if (!article || !selectedText) return;
    const note: Note = {
      id: '', // will be generated by addNote
      articleId: article.id,
      paragraphIndex: 0,
      content: selectedText,
      createdAt: '', // will be generated by addNote
      updatedAt: '', // will be generated by addNote
    };
    addToNotes(note);
    setShowNoteToolbar(false);
    setSelectedText('');
    window.getSelection()?.removeAllRanges();
  };

  // 关闭笔记工具栏
  const handleCloseNoteToolbar = () => {
    setShowNoteToolbar(false);
    setSelectedText('');
    window.getSelection()?.removeAllRanges();
  };

  // 删除笔记
  const handleDeleteNote = (noteId: string) => {
    removeFromNotes(noteId);
  };

  // 格式化时间
  const formatTime = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleDateString('zh-CN', {
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const isFavorited = article ? isArticleFavorited(article.id) : false;
  const hasBookmark = article ? isBookmarked(article.id) : false;

  const handleWordClick = (word: string, sentence: string) => {
    setSelectedWord(word);
    setSelectedSentence(sentence);
  };

  const handleCloseModal = () => {
    setSelectedWord('');
    setSelectedSentence('');
  };

  const handleToggleFavorite = () => {
    if (!article) return;

    if (isFavorited) {
      removeFromFavoriteArticles(article.id);
    } else {
      const favoriteArticle: FavoriteArticle = {
        id: Date.now().toString(),
        articleId: article.id,
        title: article.title,
        titleZh: article.titleZh,
        level: article.level,
        author: article.author,
        createdAt: new Date().toISOString(),
      };
      addToFavoriteArticles(favoriteArticle);
    }
  };

  const handleAddBookmark = () => {
    if (!article) return;

    const bookmark: BookmarkType = {
      id: Date.now().toString(),
      articleId: article.id,
      articleTitle: article.title,
      articleTitleZh: article.titleZh,
      position: 0,
      createdAt: new Date().toISOString(),
    };
    addToBookmarks(bookmark);
  };

  if (!article) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-8 h-8 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-gray-500">加载中...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <Header showBack title={article.titleZh} />

      {/* 操作按钮 */}
      <div className="fixed top-14 right-0 z-30 bg-white/95 backdrop-blur-sm border-b border-gray-100 py-2 px-3 flex items-center space-x-2 md:top-14">
        <button
          onClick={handleToggleFavorite}
          className={`p-2 rounded-full transition-all ${
            isFavorited
              ? 'bg-red-100 text-red-500'
              : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
          }`}
          title={isFavorited ? '取消收藏' : '收藏文章'}
        >
          {isFavorited ? (
            <Heart className="w-5 h-5 fill-current" />
          ) : (
            <Heart className="w-5 h-5" />
          )}
        </button>
        <button
          onClick={handleAddBookmark}
          className={`p-2 rounded-full transition-all ${
            hasBookmark
              ? 'bg-indigo-100 text-indigo-500'
              : 'bg-gray-100 text-gray-400 hover:bg-gray-200'
          }`}
          title={hasBookmark ? '已添加书签' : '添加书签'}
        >
          {hasBookmark ? (
            <Bookmark className="w-5 h-5 fill-current" />
          ) : (
            <Bookmark className="w-5 h-5" />
          )}
        </button>
      </div>

      <main
        className="pt-24 pb-8 px-3 sm:px-4 max-w-3xl mx-auto min-h-screen"
        onMouseUp={handleTextSelection}
        onTouchEnd={handleTextSelection}
      >
        <Reader article={article} onWordClick={handleWordClick} />
      </main>

      {/* 文章底部查看笔记按钮 */}
      {articleNotes.length > 0 && (
        <div className="fixed bottom-4 left-1/2 transform -translate-x-1/2 z-30">
          <button
            onClick={() => setShowNotesList(!showNotesList)}
            className={`flex items-center space-x-2 px-4 py-2 rounded-full shadow-lg transition-all ${
              darkMode
                ? 'bg-gray-800 text-white hover:bg-gray-700'
                : 'bg-white text-gray-700 hover:bg-gray-100'
            }`}
          >
            <FileText className="w-4 h-4" />
            <span className="text-sm font-medium">查看笔记 ({articleNotes.length})</span>
          </button>
        </div>
      )}

      {/* 笔记列表面板 */}
      {showNotesList && (
        <div className={`fixed inset-0 z-50 ${darkMode ? 'bg-gray-900/80' : 'bg-black/40'}`}>
          <div
            className={`absolute bottom-0 left-0 right-0 max-h-[70vh] rounded-t-2xl overflow-hidden transition-all ${
              darkMode ? 'bg-gray-800' : 'bg-white'
            }`}
          >
            {/* 列表头部 */}
            <div className={`flex items-center justify-between px-4 py-3 border-b ${darkMode ? 'border-gray-700' : 'border-gray-200'}`}>
              <h3 className={`font-semibold ${darkMode ? 'text-white' : 'text-gray-800'}`}>
                笔记列表 ({articleNotes.length})
              </h3>
              <button
                onClick={() => setShowNotesList(false)}
                className={`p-1 rounded-full ${darkMode ? 'hover:bg-gray-700 text-gray-400' : 'hover:bg-gray-100 text-gray-500'}`}
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            {/* 笔记列表 */}
            <div className="overflow-y-auto max-h-[60vh] p-4 space-y-3">
              {articleNotes.map(note => (
                <div
                  key={note.id}
                  className={`p-3 rounded-lg ${darkMode ? 'bg-gray-700' : 'bg-gray-100'}`}
                >
                  <div className="flex items-start justify-between">
                    <p className={`text-sm flex-1 ${darkMode ? 'text-gray-200' : 'text-gray-700'}`}>
                      {note.content}
                    </p>
                    <button
                      onClick={() => handleDeleteNote(note.id)}
                      className={`ml-2 p-1 rounded-full hover:bg-red-100 transition-colors flex-shrink-0 ${
                        darkMode ? 'text-gray-500 hover:text-red-400' : 'text-gray-400 hover:text-red-500'
                      }`}
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                  <p className={`text-xs mt-2 ${darkMode ? 'text-gray-500' : 'text-gray-400'}`}>
                    {formatTime(note.createdAt)}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* 浮动笔记工具栏 - 选中文字时显示在底部 */}
      {showNoteToolbar && (
        <div
          className="fixed bottom-6 left-1/2 transform -translate-x-1/2 z-50"
          style={{ transform: 'translateX(-50%)' }}
        >
          <div className={`flex items-center space-x-2 px-4 py-2 rounded-full shadow-xl ${
            darkMode ? 'bg-indigo-600' : 'bg-indigo-500'
          }`}>
            <button
              onClick={handleAddToNotes}
              className="flex items-center space-x-2 text-white"
            >
              <FileText className="w-4 h-4" />
              <span className="text-sm font-medium">添加到笔记</span>
            </button>
            <div className={`w-px h-4 ${darkMode ? 'bg-indigo-400' : 'bg-indigo-300'}`} />
            <button
              onClick={handleCloseNoteToolbar}
              className="text-white/80 hover:text-white p-1"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* 提示收藏成功 */}
      {isFavorited && (
        <div className="fixed top-24 left-1/2 transform -translate-x-1/2 z-40 bg-green-500 text-white px-4 py-2 rounded-full shadow-lg flex items-center space-x-2 animate-fadeIn md:top-20">
          <Check className="w-4 h-4" />
          <span className="text-sm">已收藏到我的收藏</span>
        </div>
      )}

      {/* 提示书签成功 */}
      {hasBookmark && (
        <div className="fixed top-24 left-1/2 transform -translate-x-1/2 z-40 bg-indigo-500 text-white px-4 py-2 rounded-full shadow-lg flex items-center space-x-2 animate-fadeIn md:top-20">
          <Check className="w-4 h-4" />
          <span className="text-sm">已添加书签</span>
        </div>
      )}

      {/* 查词浮层 */}
      {selectedWord && (
        <DictionaryModal
          word={selectedWord}
          sentence={selectedSentence}
          articleTitle={article.title}
          onClose={handleCloseModal}
        />
      )}
    </div>
  );
};

export default ArticleReaderPage;
